#!/usr/bin/env ruby

def main
  require 'optparse'
  require "pathname"
  require "json"

  options = {
    repository: "swift",
  }
  OptionParser.new do |opts|
    opts.banner = "Usage: git-swift-update-patch [options]"

    opts.on("-s", "--scheme SCHEME", "The scheme to use") do |v|
      options[:scheme] = v
    end

    opts.on("-R", "--repository REPOSITORY", "The repository to use") do |v|
      options[:repository] = v
    end
  end.parse!

  if options[:scheme].nil?
    puts "Please specify a scheme"
    exit 1
  end

  manifest = JSON.parse(File.read(File.join(File.dirname(__FILE__), '../schemes', options[:scheme], 'manifest.json')))

  patches_path = File.absolute_path(File.join(File.dirname(__FILE__), '../schemes', options[:scheme], options[:repository]))
  upstream_rev = manifest['base-tag']

  Dir.chdir(File.join(File.dirname(__FILE__), '..')) do
    Kernel.system(*[
      'git', '-C', "../" + options[:repository],
      'format-patch', '--no-numbered', upstream_rev,
      "-o", Pathname.new(patches_path).relative_path_from(File.absolute_path("../" + options[:repository])).to_s,
    ], exception: true)
  end
end

main if __FILE__ == $0
