on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
jobs:
  update-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./tools/gh-pr-update-snapshot --no-interactive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
