on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
jobs:
  update-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: ./tools/gh-pr-update-snapshot --no-interactive
        env:
          GITHUB_TOKEN: ${{ secrets.SWIFTWASM_BOT_GITHUB_TOKEN }}
